namespace RiotClub.FireMoth.Services.FileScanning
{
    using System.IO.Abstractions;

    /// <summary>
    /// Defines the public interface for a class that specifies options used during a file scan.
    /// </summary>
    public interface IScanOptions
    {
        /// <summary>
        /// Gets the directory to be scanned.
        /// </summary>
        public IDirectoryInfo ScanDirectory { get; }

        /// <summary>
        /// Gets a value indicating whether subdirectories of <see cref="ScanDirectory"/> will be
        /// recursively scanned.
        /// </summary>
        public bool RecursiveScan { get; }

        /// <summary>
        /// Gets an <see cref="OutputOption"/> value that controls the type of output generated by
        /// the file scan.
        /// </summary>
        public OutputOption OutputOption { get; }
    }
}
