//<autogenerated/>
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[module: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Rule does not apply to unit test functions.", Scope = "module")]
[module: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CS1591:Missing XML comment for publicly visible type or member", Justification = "Rule does not apply to unit test functions.", Scope = "module")]
[module: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Rule does not apply to unit test classes.", Scope = "module")]
[module: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "Conflicts with SA1000KeywordsMustBeSpacedCorrectly", Scope = "module")]