// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiotClub.FireMoth.Services.DataAccess.Sqlite;

#nullable disable

namespace RiotClub.FireMoth.Services.Migrations
{
    [DbContext(typeof(FireMothContext))]
    [Migration("20230809162850_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("RiotClub.FireMoth.Services.Repository.FileFingerprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64Hash")
                        .IsRequired()
                        .HasColumnType("char(44)");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileFingerprints");
                });
#pragma warning restore 612, 618
        }
    }
}
